name: Build and Publish Docker Image

# 在主分支有 Push 或 Pull Request 时触发构建
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      # 1. 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 登录 GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      # 3. 构建 Docker 镜像
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.IMAGE_NAME }}:${{ github.sha }}
            ${{ secrets.IMAGE_NAME }}:latest

